pool:
  vmImage: 'vs2017-win2016'

steps:
# Get Boost
- powershell: |
    Set-PSDebug -Trace 1
    $src = "https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.zip"
    $src_name = [System.IO.Path]::GetFileName($src)
    $cwd = Convert-Path "."
    $tmp_dir = Join-Path $cwd "tmp"
    mkdir $tmp_dir
    $dest_file = Join-Path $tmp_dir $src_name
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    $wc = New-Object System.Net.WebClient
    $wc.DownloadFile($src, $dest_file)
    $file_name_no_ext = [System.IO.Path]::GetFileNameWithoutExtension($src_name)
    $unzip_dest = Join-Path $tmp_dir $file_name_no_ext
    Expand-Archive $dest_file -DestinationPath $unzip_dest

- powershell: 'ls; ls tmp; ls tmp/boost_1_67_0'
  displayName: Debug

- powershell: 'mkdir build'
  displayName: Make build dir

- powershell: 'cd build; cmake -DBoost_INCLUDE_DIR=../tmp/boost_1_67_0/boost_1_67_0  ..'
  displayName: CMake

- powershell: 'cd build; msbuild ALL_BUILD.vcxproj'
  displayName: MSBuild

- powershell: 'cd build; ctest -C debug'
  displayName: Quick test

- powershell: 'cd build; time TEST_DIR=../3rdparty/test_cases/ ./evm_tests -ns -d'
  displayName: Full tests
